spring:
  application:
    name: Board_Project

  datasource:
    url: jdbc:mysql://localhost:3307/exam
    username: jeon
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
